name: Waka Trigger Test

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * 0"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore repo cache
        uses: actions/cache@v4
        with:
          path: .repo_cache
          key: repo-cache-${{ github.run_id }}
          restore-keys: |
            repo-cache-

      - uses: ImBIOS/waka-readme-stats@master
        with:
          SHOW_PROJECTS: "False"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: CodingStats
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics

      - name: Save repo cache
        if: always()
        uses: actions/cache@v4
        with:
          path: .repo_cache
          key: repo-cache-${{ github.run_id }}

  rerun-failed-jobs:
    runs-on: ubuntu-latest
    needs: [update-readme]
    if: failure()
    steps:
      - name: Rerun failed jobs in the current workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh run rerun ${{ github.run_id }} --failed
